spring:
  profiles:
    active: dev
  main:
    banner-mode: off

logging:
  config: classpath:log4j2.yml
  level:
    org:
      springframework: INFO

window:
  width: 1600
  height: 900
  title: "Lunix java game"
  maximized: true

resources:
  shaders:
    default: assets/shaders/default.glsl
    debug: assets/shaders/debug.glsl
    picking: assets/shaders/picking.glsl
  textures:
    player_idle:
      path: assets/images/player_idle.png
      width: 40
      height: 50
    tile_brick:
      path: assets/images/tile_brick.png
      width: 64
      height: 64
    arrow:
      path: assets/images/arrow.png
  sounds:
    player_hit:
      path: assets/sounds/player_hit.ogg
      loops: false

camera:
  ortho:
    width: 48
    height: 27
  prespective:
    field-of-view: 45
  x-offset: -13
  y-offset: -13
  z-offset: 13
  z-near: 1
  z-far: 5000

paths:
  save:
    levels: src/main/resources/levels
    
editor:
  grid_size: 10

