spring:
  profiles:
    active: dev
  main:
    banner-mode: off

logging:
  config: classpath:log4j2.yml
  level:
    org:
      springframework: INFO

window:
  width: 1280
  height: 720
  title: "Lunix java game"
  maximized: true
  
resources:
  shaders:
    default: assets/shaders/default.glsl
  textures:
    player: assets/images/Player.png
    enemy: assets/images/Enemy.png
    player_idle: assets/images/Player-idle.png
  sprite-sheet:
    -
      texture: enemy
      width: 152
      height: 512
    -
      texture: player_idle
      width: 40
      height: 50
    
camera:
  ortho:
    width: 320
    height: 180
  prespective:
    field-of-view: 45
  x-offset: -100
  y-offset: -100
  z-offset: 100
  z-near: 10
  z-far: 500
  
paths:
  save:
    levels: levels
