spring:
  profiles:
    active: dev
  main:
    banner-mode: off

logging:
  config: classpath:log4j2.yml
  level:
    org:
      springframework: INFO

window:
  width: 1280
  height: 720
  title: "Lunix java game"
  maximized: true
  
resources:
  shaders:
    default: assets/shaders/default.glsl
    noPerspective: assets/shaders/noPerspective.glsl
    
camera:
  ortho:
    width: 320
    height: 180
  prespective:
    field-of-view: 60
  x-offset: 0
  y-offset: -100
  z-offset: 100
  z-near: 0
  z-far: 500