spring:
  profiles:
    active: dev
  main:
    banner-mode: off

logging:
  config: classpath:log4j2.yml
  level:
    org:
      springframework: INFO

window:
  width: 1280
  height: 720
  title: "Lunix java game"
  maximized: true

resources:
  shaders:
    default: assets/shaders/default.glsl
    debug: assets/shaders/debug.glsl
  textures:
    player:
      path: assets/images/Player.png
    enemy:
      path: assets/images/Enemy.png
      width: 152
      height: 512
    player_idle:
      path: assets/images/player_idle.png
      width: 40
      height: 50
    tile_brick:
      path: assets/images/tile_brick.png
      width: 64
      height: 64

camera:
  ortho:
    width: 320
    height: 180
  prespective:
    field-of-view: 45
  x-offset: -100
  y-offset: -100
  z-offset: 100
  z-near: 10
  z-far: 500

paths:
  save:
    levels: src/main/resources/levels
    
editor:
  grid_size: 100

