spring:
  profiles:
    active: dev
  main:
    banner-mode: off

logging:
  config: classpath:log4j2.yml
  level:
    org:
      springframework: INFO

window:
  height: 1280
  width: 720
  title: "Lunix java game"
  maximized: true
  
resources:
  shaders:
    default: assets/shaders/default.glsl