spring:
  profiles:
    active: dev
  main:
    banner-mode: off

logging:
  level:
    org:
      springframework:
        test: INFO

window:
  height: 1280
  width: 720
  title: "Lunix java game"
  maximized: true